# Generated by Django 4.2.13 on 2026-05-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('stripe', 'Stripe (Tarjeta)'), ('transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado')], default='pending', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_evidences/%Y/%m/')),
                ('file_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Evidencia de pago',
                'verbose_name_plural': 'Evidencias de pago',
            },
        ),
    ]
